### ISSUE TITLE
PV plant location

### ISSUE THREAD

**Issue by hohlb** [zuzfil/PV-Optimisation#1]
Hi,

Thank you for sharing the data!

Could you tell us the **location** of three power plants? We would like to correlate them with weather data to achieve a kind of predictive maintenance (is the plant working as expected). 

Thank you!

**Comment by zuzfil** [comment]
Hi there,

Let me check with the data originator and I will get back to you.

Kind regards,
Zuzana

**Comment by zuzfil** [comment]
All three plants are located in Aargau. Does that answer your question, please?

**Comment by hohlb** [comment]
Great, that does answer the question.
Thank you.
